name: Playwright Tests

on:
  push:
    branches:
      - main
  schedule:
    - cron: '00 11 * * *'  # Runs every day at 11:00 AM UTC

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      issues: write  # ✅ Grants permission to create issues

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Environment Variables
        run: echo "BASE_URL=${{ secrets.BASE_URL }}" >> $GITHUB_ENV

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t benpavey-tests .

      - name: Run Tests in Docker (Pass BASE_URL)
        run: |
          docker run --rm \
            -e BASE_URL="${{ env.BASE_URL }}" \
            -v ${{ github.workspace }}/playwright-report:/app/playwright-report \
            benpavey-tests

      - name: Upload Playwright Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-report
          path: playwright-report/

      - name: Create GitHub Issue on Failure
        if: failure()
        uses: JasonEtco/create-an-issue@v2
        with:
          filename: .github/ISSUE_TEMPLATE/test-failure.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Issue on Success
        if: success()
        uses: JasonEtco/create-an-issue@v2
        with:
          filename: .github/ISSUE_TEMPLATE/test-success.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Issue on Skipped Tests
        if: steps.playwright-tests.outcome == 'skipped'
        uses: JasonEtco/create-an-issue@v2
        with:
          filename: .github/ISSUE_TEMPLATE/test-skipped.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
