name: Playwright Tests

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 10 * * *'  # Daily at 10:00 AM GMT

permissions:
  contents: write  # Allow pushing changes (e.g., GitHub Pages reports)
  issues: write    # Allow creating GitHub issues

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ secrets.BASE_URL }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          npm install
          npx playwright install --with-deps

      - name: Run Playwright Tests
        run: |
          npx playwright test --reporter=html

      - name: Upload Playwright Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-report
          path: playwright-report/
          retention-days: 7  # Keep test reports for 7 days

      - name: Deploy Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report
          destination_dir: reports
          keep_files: true

      # Notify via GitHub Issue for Test Success
      - name: Create Issue if Tests Passed
        if: success()
        uses: JasonEtco/create-an-issue@v2
        with:
          filename: .github/ISSUE_TEMPLATE/test-success.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Notify via GitHub Issue for Test Failure
      - name: Create Issue if Tests Failed
        if: failure()
        uses: JasonEtco/create-an-issue@v2
        with:
<<<<<<< HEAD
          filename: .github/ISSUE_TEMPLATE/test-failed.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
=======
          filename: .github/ISSUE_TEMPLATE/test-failure.md
>>>>>>> d9c75976049d54551afef5629b0a915e28082120
